# Generated by Django 4.2 on 2023-05-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
