# Generated by Django 4.2 on 2023-05-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mypet', '0002_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('tel', models.IntegerField()),
                ('gmail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
