# Generated by Django 4.2 on 2023-05-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0004_customuser_delete_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
