# Generated by Django 4.2 on 2023-05-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0009_ads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
