# Generated by Django 4.2 on 2023-05-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0011_ads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
